### ISSUE TITLE
[Bug]: Helm部署EC模式启动失败，blobstore镜像不匹配

### ISSUE THREAD

**Issue by mjhalxx** [cubefs/cubefs#3634]
### Is there an existing issue for this?

- [X] I have searched all the existing issues

### Priority

high

### Environment

```markdown
- CubeFS version: v3.4.0
- Deployment mode(docker or standalone or cluster): k8s
- Dependent components: clustermgr,blobnode,proxy,scheduler
- OS kernel version(Ubuntu or CentOS): centOS
- CPU/Memory:
- Others:
```

### Current Behavior

使用 最新 helm-chart 部署 cubefs，启用 blobstore 模式：  
```yaml
# Select which component to install
component:
  master: true
  datanode: false
  metanode: true
  objectnode: true
  client: true
  csi: true
  monitor: true
  ingress: true
  blobstore_clustermgr: true
  blobstore_blobnode: true
  blobstore_proxy: true
  blobstore_scheduler: true
  blobstore_access: true

image:
  server: cubefs/cfs-server:v3.4.0
  client: cubefs/cfs-client:v3.4.0
  blobstore: cubefs/blobstore:v3.4.0
```
部署后 blobstore_clustermgr、blobstore_blobnode、blobstore_proxy、blobstore_scheduler、blobstore_access 均启动失败，查看blobstore_clustermgr 日志报错为```/cfs/bin/start_clustermgr.sh:No such file or directory```  
查看 blobstore 的 dockerfile 看该镜像只提供了 ```start_docker.sh```启动脚本，并且没有 ```/cfs/bin/```目录  
进一步查看 chart 中 blobstore_blobnode、blobstore_proxy、blobstore_scheduler、blobstore_access 均需提供对应的启动脚本，且放到```/cfs/bin```目录下

### Expected Behavior

提供一个可用于 chart 部署的 blobstore 镜像
